package edu.zju.ccnt.orginazation.model;

import java.util.Date;

public class Orginazation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orginazation.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orginazation.orginazation_name
     *
     * @mbg.generated
     */
    private String orginazationName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orginazation.orginazation_address
     *
     * @mbg.generated
     */
    private String orginazationAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orginazation.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orginazation.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orginazation.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orginazation.parent_id
     *
     * @mbg.generated
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orginazation.checked
     *
     * @mbg.generated
     */
    private Integer checked;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orginazation.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orginazation.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orginazation.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orginazation.id
     *
     * @return the value of orginazation.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orginazation.id
     *
     * @param id the value for orginazation.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orginazation.orginazation_name
     *
     * @return the value of orginazation.orginazation_name
     *
     * @mbg.generated
     */
    public String getOrginazationName() {
        return orginazationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orginazation.orginazation_name
     *
     * @param orginazationName the value for orginazation.orginazation_name
     *
     * @mbg.generated
     */
    public void setOrginazationName(String orginazationName) {
        this.orginazationName = orginazationName == null ? null : orginazationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orginazation.orginazation_address
     *
     * @return the value of orginazation.orginazation_address
     *
     * @mbg.generated
     */
    public String getOrginazationAddress() {
        return orginazationAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orginazation.orginazation_address
     *
     * @param orginazationAddress the value for orginazation.orginazation_address
     *
     * @mbg.generated
     */
    public void setOrginazationAddress(String orginazationAddress) {
        this.orginazationAddress = orginazationAddress == null ? null : orginazationAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orginazation.description
     *
     * @return the value of orginazation.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orginazation.description
     *
     * @param description the value for orginazation.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orginazation.phone
     *
     * @return the value of orginazation.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orginazation.phone
     *
     * @param phone the value for orginazation.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orginazation.email
     *
     * @return the value of orginazation.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orginazation.email
     *
     * @param email the value for orginazation.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orginazation.parent_id
     *
     * @return the value of orginazation.parent_id
     *
     * @mbg.generated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orginazation.parent_id
     *
     * @param parentId the value for orginazation.parent_id
     *
     * @mbg.generated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orginazation.checked
     *
     * @return the value of orginazation.checked
     *
     * @mbg.generated
     */
    public Integer getChecked() {
        return checked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orginazation.checked
     *
     * @param checked the value for orginazation.checked
     *
     * @mbg.generated
     */
    public void setChecked(Integer checked) {
        this.checked = checked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orginazation.remarks
     *
     * @return the value of orginazation.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orginazation.remarks
     *
     * @param remarks the value for orginazation.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orginazation.update_time
     *
     * @return the value of orginazation.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orginazation.update_time
     *
     * @param updateTime the value for orginazation.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orginazation.create_time
     *
     * @return the value of orginazation.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orginazation.create_time
     *
     * @param createTime the value for orginazation.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }


}