package edu.zju.ccnt.order.model;

import java.math.BigDecimal;
import java.util.Date;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_order.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_order.order_no
     *
     * @mbg.generated
     */
    private String orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_order.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_order.service_id
     *
     * @mbg.generated
     */
    private Integer serviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_order.service_name
     *
     * @mbg.generated
     */
    private String serviceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_order.buy_time
     *
     * @mbg.generated
     */
    private Date buyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_order.format
     *
     * @mbg.generated
     */
    private String format;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_order.apikey
     *
     * @mbg.generated
     */
    private String apikey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_order.quantity
     *
     * @mbg.generated
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_order.total_call
     *
     * @mbg.generated
     */
    private Integer totalCall;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_order.can_call
     *
     * @mbg.generated
     */
    private Integer canCall;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_order.use_call
     *
     * @mbg.generated
     */
    private Integer useCall;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_order.score
     *
     * @mbg.generated
     */
    private BigDecimal score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_order.total_price
     *
     * @mbg.generated
     */
    private BigDecimal totalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_order.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_order.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_order.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_order.id
     *
     * @return the value of service_order.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_order.id
     *
     * @param id the value for service_order.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_order.order_no
     *
     * @return the value of service_order.order_no
     *
     * @mbg.generated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_order.order_no
     *
     * @param orderNo the value for service_order.order_no
     *
     * @mbg.generated
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_order.user_id
     *
     * @return the value of service_order.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_order.user_id
     *
     * @param userId the value for service_order.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_order.service_id
     *
     * @return the value of service_order.service_id
     *
     * @mbg.generated
     */
    public Integer getServiceId() {
        return serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_order.service_id
     *
     * @param serviceId the value for service_order.service_id
     *
     * @mbg.generated
     */
    public void setServiceId(Integer serviceId) {
        this.serviceId = serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_order.service_name
     *
     * @return the value of service_order.service_name
     *
     * @mbg.generated
     */
    public String getServiceName() {
        return serviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_order.service_name
     *
     * @param serviceName the value for service_order.service_name
     *
     * @mbg.generated
     */
    public void setServiceName(String serviceName) {
        this.serviceName = serviceName == null ? null : serviceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_order.buy_time
     *
     * @return the value of service_order.buy_time
     *
     * @mbg.generated
     */
    public Date getBuyTime() {
        return buyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_order.buy_time
     *
     * @param buyTime the value for service_order.buy_time
     *
     * @mbg.generated
     */
    public void setBuyTime(Date buyTime) {
        this.buyTime = buyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_order.format
     *
     * @return the value of service_order.format
     *
     * @mbg.generated
     */
    public String getFormat() {
        return format;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_order.format
     *
     * @param format the value for service_order.format
     *
     * @mbg.generated
     */
    public void setFormat(String format) {
        this.format = format == null ? null : format.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_order.apikey
     *
     * @return the value of service_order.apikey
     *
     * @mbg.generated
     */
    public String getApikey() {
        return apikey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_order.apikey
     *
     * @param apikey the value for service_order.apikey
     *
     * @mbg.generated
     */
    public void setApikey(String apikey) {
        this.apikey = apikey == null ? null : apikey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_order.quantity
     *
     * @return the value of service_order.quantity
     *
     * @mbg.generated
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_order.quantity
     *
     * @param quantity the value for service_order.quantity
     *
     * @mbg.generated
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_order.total_call
     *
     * @return the value of service_order.total_call
     *
     * @mbg.generated
     */
    public Integer getTotalCall() {
        return totalCall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_order.total_call
     *
     * @param totalCall the value for service_order.total_call
     *
     * @mbg.generated
     */
    public void setTotalCall(Integer totalCall) {
        this.totalCall = totalCall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_order.can_call
     *
     * @return the value of service_order.can_call
     *
     * @mbg.generated
     */
    public Integer getCanCall() {
        return canCall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_order.can_call
     *
     * @param canCall the value for service_order.can_call
     *
     * @mbg.generated
     */
    public void setCanCall(Integer canCall) {
        this.canCall = canCall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_order.use_call
     *
     * @return the value of service_order.use_call
     *
     * @mbg.generated
     */
    public Integer getUseCall() {
        return useCall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_order.use_call
     *
     * @param useCall the value for service_order.use_call
     *
     * @mbg.generated
     */
    public void setUseCall(Integer useCall) {
        this.useCall = useCall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_order.score
     *
     * @return the value of service_order.score
     *
     * @mbg.generated
     */
    public BigDecimal getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_order.score
     *
     * @param score the value for service_order.score
     *
     * @mbg.generated
     */
    public void setScore(BigDecimal score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_order.total_price
     *
     * @return the value of service_order.total_price
     *
     * @mbg.generated
     */
    public BigDecimal getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_order.total_price
     *
     * @param totalPrice the value for service_order.total_price
     *
     * @mbg.generated
     */
    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_order.status
     *
     * @return the value of service_order.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_order.status
     *
     * @param status the value for service_order.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_order.create_time
     *
     * @return the value of service_order.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_order.create_time
     *
     * @param createTime the value for service_order.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_order.update_time
     *
     * @return the value of service_order.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_order.update_time
     *
     * @param updateTime the value for service_order.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}