package edu.zju.ccnt.orginazation.dao;

import edu.zju.ccnt.orginazation.model.Orginazation;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface OrginazationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orginazation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orginazation
     *
     * @mbg.generated
     */
    int insert(Orginazation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orginazation
     *
     * @mbg.generated
     */
    int insertSelective(Orginazation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orginazation
     *
     * @mbg.generated
     */
    Orginazation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orginazation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Orginazation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orginazation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Orginazation record);

    int selectByOrginazationName(String name);

    int selectByOrginazationNameAndId(@Param("name") String name, @Param("orginazationId") Integer orginazationId);

    List<Orginazation> selectBySuperAdmin(@Param("checked")Integer checked);


    /**
    一个根据id获得组织名
     */
    String selectNameById(@Param("orginazationId") Integer orginazationId);

}