package edu.zju.ccnt.service.dao;

import edu.zju.ccnt.service.model.Service;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ServiceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service
     *
     * @mbg.generated
     */
    int insert(Service record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service
     *
     * @mbg.generated
     */
    int insertSelective(Service record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service
     *
     * @mbg.generated
     */
    Service selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Service record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Service record);

    List<Service> selectByEnterpriseId(Integer userId);     //查找已经审核过的且还在架上的服务

    int selectByServiceName(String serviceName);

    //这里对查询服务列表做缓存，在对服务进行删除、修改、添加时缓存无效，需重新查询
    List<Service> selectServiceList(@Param("serviceName") String serviceName, @Param("orderBy") String orderBy, @Param("categoryId") Integer categoryId);

    int selectByServiceNameAndServiceId(@Param("serviceName") String serviceName,@Param("serviceId")Integer serviceId);

    List<Service> selectByServiceNameAndUserList(@Param("serviceName") String serviceName,@Param("userList")List<Integer> userList,@Param("checked")Integer checked);

    List<Service> selectBySuperAdmin(@Param("serviceName") String serviceName,@Param("checked") Integer checked,@Param("userList") List<Integer> userList);

    //按服务id列表查询所有服务信息
    List<Service> selectByServiceIdList(@Param("serviceIdList") List<Integer> serviceIdList);

    List<Service> selectThirdByServiceName(@Param("serviceName")String serviceName,@Param("isOther")Integer isOther);

    List<Integer> selectServiceByUserLists(@Param("userList") List<Integer> userList /*, @Param("checked") Integer checked*/);

    int selectAllChecked();

    List<Integer> selectServiceByName(String name);
}