package edu.zju.ccnt.service.dao;

import edu.zju.ccnt.service.model.ServiceCategory;

import java.util.List;

public interface ServiceCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_category
     *
     * @mbg.generated
     */
    int insert(ServiceCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_category
     *
     * @mbg.generated
     */
    int insertSelective(ServiceCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_category
     *
     * @mbg.generated
     */
    ServiceCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ServiceCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ServiceCategory record);

    List<ServiceCategory> list();
}